name: Scraper
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  Run_codepen_scrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Go to root directory
        run: cd ../
      - name: Build
        run: npm run build
      - name: Start
        run: npm run start
    
     
