name: Scraper
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  Run_codepen_scrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: list files
        run: ls       
      - name: Build
        run: npm run build
      - name: change
        run: cd dist
      - name: list files
        run: ls 
      - name: run
        run: node index.js    
     
