name: Scraper
on:
  schedule:
    - cron: '*/5 * * * *'
    # - cron: "0 */6 * * *"   
jobs:
  Run_codepen_scrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Logs
        run: "echo ${{ vars.DATABASE_URL }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: list files
        run: ls       
      - name: Build
        run: npm run build
      - run: pwd
      - run: ls -la dist/github_actions
      - name: run
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
          SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
          RECEIVER_EMAIL: ${{secrets.RECEIVER_EMAIL}}
          CODEPEN_PROFILE: ${{secrets.CODEPEN_PROFILE}}
          PORT: ${{secrets.PORT}}
        run: npm run perform-codepen-operations  
     
