on:
  schedule:
    - cron: '*/5 * * * *'  # Run every minute

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to version 3

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Update to version 4
        with:
          node-version: '16'  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Run scraping
        run: npm start
